### ISSUE TITLE
When file contains danish letters æøå the conversion won't happen.

### ISSUE THREAD

**Issue by Poetastrophe** [patrickdavey/vimwiki_markdown#44] opened 2022-08-12 09:32 UTC
When file contains danish letters æøå the conversion won't happen.

To reproduce:
1. make a markdown file in your vimwiki folder (here I called it test2.md)
2. When I write the following and run Vimwiki2HTML from nvim 
```md
1. ø
```
3. I get the following error:
```txt
Vimwiki: '/home/chris/.local/share/gem/ruby/3.1.0/gems/vimwiki_markdown-0.8.2/lib/vimwiki_markdown/wiki_body.rb:52:in `gsub!'': invalid byte sequence in US-ASC
II (ArgumentError)
        from /home/chris/.local/share/gem/ruby/3.1.0/gems/vimwiki_markdown-0.8.2/lib/vimwiki_markdown/wiki_body.rb:52:in `convert_wiki_style_links_with_title_b
ar!''
        from /home/chris/.local/share/gem/ruby/3.1.0/gems/vimwiki_markdown-0.8.2/lib/vimwiki_markdown/wiki_body.rb:45:in `fixlinks''
        from /home/chris/.local/share/gem/ruby/3.1.0/gems/vimwiki_markdown-0.8.2/lib/vimwiki_markdown/wiki_body.rb:18:in `to_s''
        from /home/chris/.local/share/gem/ruby/3.1.0/gems/vimwiki_markdown-0.8.2/lib/vimwiki_markdown.rb:16:in `convert_wikimarkdown_to_html''
        from /home/chris/.local/share/gem/ruby/3.1.0/gems/vimwiki_markdown-0.8.2/bin/vimwiki_markdown:4:in `<top (required)>''
        from /home/chris/.local/share/gem/ruby/3.1.0/bin/vimwiki_markdown:25:in `load''
        from /home/chris/.local/share/gem/ruby/3.1.0/bin/vimwiki_markdown:25:in `<main>''
'
Vimwiki: HTML conversion is done, output: /home/chris/life/site_html/
```

**Comment by Poetastrophe** [comment] 2022-08-12 09:53
Things magically work when I use
```
$ export RUBYOPT="-KU -E utf-8:utf-8"
```
I don't understand why ;)

**Comment by patrickdavey** [comment] 2022-08-12 10:01
Ah very good. I'll see what I can do. I'm away on holidays at the moment so
it'll be at least a week. I'm also surprised the string isn't utf8 by
default.

**Comment by patrickdavey** [comment] 2022-08-18 11:26
This is a little bit interesting. I don't _quite_ understand how the input file is being treated like that. Can you attach the .md file here, I'm just curious to see exactly how it is encoded.

Also, can you run vim and then type `:set fileencodings` and let me know what it prints out.

Bit strange. I tried copying that text into a file and converting it. Mine correctly was written out as UTF-8 and converted fine.

What operating system are you using?

**Comment by patrickdavey** [comment] 2023-03-15 22:18
Closing as cannot reproduce.  Please re-open if you can either supply the file / give steps to reproduce :)

**Closed by patrickdavey** 2023-03-15 22:18 UTC
